name: Java CI-CD with Gradle

on:
  push:
    tags:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Pull & Checkout"
        uses: https://ssl.lunadeer.cn:14446/actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Set up JDK 17"
        uses: https://ssl.lunadeer.cn:14446/actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - name: "Config Git"
        run: |
          git config --global user.email "actions@gitea.com"
          git config --global user.name "actions"
      - name: "Apply Patches"
        run: ./gradlew applyPatches
      - name: "Build Mojmap"
        run: ./gradlew createMojmapPaperclipJar
      - name: "Copy jar to staging"
        run: mkdir staging && cp build/libs/*.jar staging
      - name: "Setup go for release script"
        run: |
          wget --no-check-certificate https://golang.google.cn/dl/go1.21.6.linux-amd64.tar.gz
          rm -rf /usr/local/go && tar -C /usr/local -xzf go1.21.6.linux-amd64.tar.gz
          ln -s /usr/local/go/bin/go /usr/bin/go
          go version
      - name: "Release"
        uses: https://ssl.lunadeer.cn:14446/zhangyuheng/release-action@main
        with:
          note: "请下载 `DeerFolia-paperclip-xxx.jar` 前缀的版本。"
          files: |-
            staging/*.jar
          api_key: '${{secrets.RELEASE_TOKEN}}'